code review please.
mfdlabs/robloxlabs.com pull request #93
Opened 2021-04-04 22:13 UTC by GithubPagesStuff

please review code. thanks. i know fixing this will take 10x longer than implementing it but oh well.

2021-04-04 22:33 UTC, rbx-nsg requested changes
You really need to learn how to do this better, a lot of this has to change, you will need to refer to the points revision, and the soon to come, auth revision in order to work on this better, or you can't really work on it

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/ApiSites/Roblox.Auth.Api/Controllers/v1/login.ts
> +		return res.status(200).send(ee)
Wtf

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/ApiSites/Roblox.Develop.Api/Controllers/v1/UploadAsset.ts
> +/*
This controller doesn't exist

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Helpers/Constants/Directories.ts
>  export const __sslDirName = __baseDirName + '\\SSL';
Make sure this is UNTRACKED, it will conflict with the main branch

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Assets/Asset.ts
> +	public static async GetFromID(Id: number) :Task<Roblox.Platform.Assets.IAsset>{
Bruh format your shttikoh1h23o12i3j123ho1

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Assets/IAsset.d.ts
> +		public Archived: Roblox.Platform.SQLBoolean;
It's just System.Boolean

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Assets/IAsset.d.ts
> +		public Archived: Roblox.Platform.SQLBoolean;
And don't modify the type declarations

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Membership/CreatorType.ts
> +declare namespace Roblox.Platform.Membership {
1. Belongs in a `.d.ts` file
2. Belongs in `Assemblies/DataV2/Core/Roblox.DataV2.Core/CreatorType.d.ts` in the namespace `Roblox.DataV2.Core`

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Membership/IUser.ts
>  import { IEmail } from '../Credentials/IEmail';
Bruh why did you modify this, this was originally a 100% accurate partial interface for IUser

2021-04-04 22:33 UTC, rbx-nsg commented on README.md
>  3. SQL Setup, for this project, it uses MySQL, you will be able to use regular MySQL, and PHPMyAdmin etc. For the Tables, you can look in the [SQL](./SQL) folder to see the CREATE commands for each t
Modifying this caused conflicts

2021-04-04 22:33 UTC, rbx-nsg commented on SQL/user.sql
> +CREATE TABLE `RobloxMembership`.`user` (
Fine with the `RobloxMembership` parts, but do not remove fields from this

2021-04-04 22:33 UTC, rbx-nsg commented on SQL/asset.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
Split this into a different .sql file

2021-04-04 22:33 UTC, rbx-nsg commented on SQL/session.sql
> +  `Created` datetime,
Why did you remove NOT NULL from these?

2021-04-04 22:33 UTC, rbx-nsg commented on SQL/user.sql
> +
Why would you remove the FK?

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Misc/SQLBoolean.ts
> +}
Remove this and use a ternary op

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Membership/User.ts
> +	public static async GetByUserPass(Username: string, Password: string): Task<IUser> {
GetByPassword

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/Platform/Assets/IAsset.d.ts
> +		public CurrentAVID: System.Int64; // just a thing to help get the asset.
Remove from production when finished

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/ApiSites/Roblox.Develop.Api/Controllers/v1/UploadAsset.ts
> +/*
It is either `data.sitetest4.robloxlabs.com/Upload.ashx` (csrf and used on the client) or `www.sitetest4.robloxlabs.com/build/upload` (csrf and captcha, used on the site)

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/ApiSites/Roblox.Auth.Api/Controllers/v1/signup.ts
> +	}
Refactor the hell out of this, it is gross to look at

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/ApiSites/Roblox.Auth.Api/Controllers/v1/login.ts
> +		return res.status(200).send(ee)
Refer to signup's comment

2021-04-04 22:33 UTC, rbx-nsg commented on Assemblies/ApiSites/Roblox.Assets.Api/Controllers/v1/asset.ts
> +		}
There are too many things you need to do here. pls do it

2021-04-04 22:42 UTC, rbx-nsg commented
The actions won't run until the conflicts are fixed

2021-04-11 00:03 UTC, GithubPagesStuff commented
cancel this, too much changes, will have to edit.

2021-04-11 00:03 UTC, closed without merging